name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t secure-app .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-app
          severity: HIGH,CRITICAL
          exit-code: 1
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image to Docker Hub
        run: |
          docker tag secure-app ${{ secrets.DOCKER_USERNAME }}/secure-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/secure-app:latest
